require('slick-carousel');
import './js/main.js';
import './js/jacket.js';
import './js/shirt.js';
import './scss/base.scss';
import './scss/style.scss';
import './scss/shirt.scss';
import './scss/typography.scss';
import './js/jeans.js';
import './scss/jeans.scss';